version: "3.9"

services:
  aplicacionjava:
    image: tomcat:${TOMCAT_VERSION}
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./${WAR_FILE}:/usr/local/tomcat/webapps/${WAR_FILE}:ro
    restart: always

  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - aplicacionjava
    restart: always
